# Generated by Django 6.0.1 on 2026-04-17 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0015_alter_news_image_alter_project_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-created_at'], 'verbose_name': 'Noticia', 'verbose_name_plural': 'Noticias'},
        ),
        migrations.AddField(
            model_name='news',
            name='title',
            field=models.CharField(default='Comunicado Académico', max_length=200, verbose_name='Título de la Noticia'),
        ),
    ]
